# docker-compose.yml
version: '2'
services:
 db:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: 
    MYSQL_ROOT_PASSWORD : root
    MYSQL_DATABASE : tpachato
    MYSQL_USER : med
    MYSQL_PASSWORD : root 
  ports: 
    - "3307:3306"
  volumes: 
    - ./db_data:/var/lib/mysql 
 app: 
  build: .
  ports: 
    - "127.0.0.1:8089:8089"
  depends_on: 
    - db
  environment: 
    SPRING_DATASOURCE_URL :  "jdbc:mysql://db:3307/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    SPRING_DATASOURCE_USERNAME :  med
    SPRING_DATASOURCE_PASSWORD :  root 

 
