# docker-compose.yml
version: '3.9'
services:
 db:
  image: mysql:5.1.73
  restart: always
  environment: 
    MYSQL_ROOT_PASSWORD : root
    MYSQL_DATABASE : tpachato
    MYSQL_USER : med
    MYSQL_PASSWORD : root 
  ports: 
    - "3307:3306"
  networks:
    - network
  volumes: 
    - ./db_app:/var/lib/mysql 
 app: 
  build: .
  ports: 
    - "127.0.0.1:8089:8089"
  depends_on: 
    - db
  environment: 
    SPRING_DATASOURCE_URL :  "jdbc:mysql://db:3307/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    SPRING_DATASOURCE_USERNAME :  root
    SPRING_DATASOURCE_PASSWORD :  root 
  networks:
    - network
networks:
  network:
 
