# docker-compose.yml
version: '3.9'
services:

 app: 
  build: .
  ports: 
    - "8089:8089"
 
  environment: 
    SPRING_DATASOURCE_URL :  "jdbc:mysql://mysql-db:3306/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    SPRING_DATASOURCE_USERNAME : "root"
    SPRING_DATASOURCE_PASSWORD : "root" 
  networks:
    - network
networks:
  network:
 
