# docker-compose.yml
version: '2'
services:
 db:
  image: mysql
  restart: always
  environment: 
    MYSQL_DATABASE : tpachato
    MYSQL_USER : "root"
    MYSQL_PASSWORD : "root" 
  volumes: 
    - ./db_data:/var/lib/mysql 
 app: 
  build: .
  ports: 
    - "127.0.0.1:8089:8089"
  depends_on: 
    - db
  environment: 
    SPRING_DATASOURCE_URL :  "jdbc:mysql://db:3306/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    SPRING_DATASOURCE_USERNAME :  "root" 
    SPRING_DATASOURCE_PASSWORD :  "root" 

 
